package ligadorps;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author João Pedro Bretanha
 */
public class FrameMontador extends javax.swing.JFrame {

    private Montador m; 
    private String seg1, seg2 = null;
    private ArrayList<ControllerUso> TabUso1, TabUso2 = null;
    private ArrayList<ControllerDefinicao> TabDef1, TabDef2 = null;
    private boolean[] reloc1, reloc2 = null;
    private String mont1, mont2 = null;

    public ArrayList<ControllerUso> getTabUso1() {
        return TabUso1;
    }

    public void setTabUso1(ArrayList<ControllerUso> TabUso1) {
        this.TabUso1 = TabUso1;
    }

    public ArrayList<ControllerUso> getTabUso2() {
        return TabUso2;
    }

    public void setTabUso2(ArrayList<ControllerUso> TabUso2) {
        this.TabUso2 = TabUso2;
    }

    public ArrayList<ControllerDefinicao> getTabDef1() {
        return TabDef1;
    }

    public void setTabDef1(ArrayList<ControllerDefinicao> TabDef1) {
        this.TabDef1 = TabDef1;
    }

    public ArrayList<ControllerDefinicao> getTabDef2() {
        return TabDef2;
    }

    public void setTabDef2(ArrayList<ControllerDefinicao> TabDef2) {
        this.TabDef2 = TabDef2;
    }

    public boolean[] getReloc1() {
        return reloc1;
    }

    public void setReloc1(boolean[] reloc1) {
        this.reloc1 = reloc1;
    }

    public boolean[] getReloc2() {
        return reloc2;
    }

    public void setReloc2(boolean[] reloc2) {
        this.reloc2 = reloc2;
    }

    public String getMont1() {
        return mont1;
    }

    public void setMont1(String mont1) {
        this.mont1 = mont1;
    }

    public String getMont2() {
        return mont2;
    }

    public void setMont2(String mont2) {
        this.mont2 = mont2;
    }
    
    public FrameMontador() {
        super("Montador");
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirSeg1 = new javax.swing.JButton();
        MontarSeg1 = new javax.swing.JButton();
        AbrirSeg2 = new javax.swing.JButton();
        MontarSeg2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabUso1Area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabDef1Area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabDef2Area = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabUso2Area = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        LocMont1 = new javax.swing.JLabel();
        LocMont2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AbrirSeg1.setText("Abrir Segmento 1");
        AbrirSeg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirSeg1ActionPerformed(evt);
            }
        });

        MontarSeg1.setText("Montar Segmento 1");
        MontarSeg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontarSeg1ActionPerformed(evt);
            }
        });

        AbrirSeg2.setText("Abrir Segmento 2");
        AbrirSeg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirSeg2ActionPerformed(evt);
            }
        });

        MontarSeg2.setText("Montar Segmento 2");
        MontarSeg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontarSeg2ActionPerformed(evt);
            }
        });

        TabUso1Area.setEditable(false);
        TabUso1Area.setColumns(20);
        TabUso1Area.setRows(5);
        jScrollPane1.setViewportView(TabUso1Area);

        jLabel1.setText("Tabela de Uso Segmento 1");

        TabDef1Area.setEditable(false);
        TabDef1Area.setColumns(20);
        TabDef1Area.setRows(5);
        jScrollPane2.setViewportView(TabDef1Area);

        jLabel2.setText("Tabela de Definição Segmento 1");

        TabDef2Area.setEditable(false);
        TabDef2Area.setColumns(20);
        TabDef2Area.setRows(5);
        jScrollPane3.setViewportView(TabDef2Area);

        jLabel3.setText("Tabela de Definição Segmento 2");

        TabUso2Area.setColumns(20);
        TabUso2Area.setRows(5);
        jScrollPane4.setViewportView(TabUso2Area);

        jLabel4.setText("Tabela de Uso Segmento 2");

        LocMont1.setText("Local do arquivo mont1");

        LocMont2.setText("Local do arquivo mont2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MontarSeg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AbrirSeg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AbrirSeg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MontarSeg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(39, 39, 39))
                                        .addComponent(jLabel4))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LocMont1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(LocMont2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbrirSeg1)
                    .addComponent(AbrirSeg2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MontarSeg1)
                    .addComponent(MontarSeg2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LocMont1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(LocMont2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirSeg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirSeg1ActionPerformed
        JFileChooser jFileChooser1;
        jFileChooser1 = new JFileChooser("entradas");   //cria o jfilechooser
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);  //mostrar apenas diretorios e arquivos
        int returnval = jFileChooser1.showOpenDialog(null); //mostra a janela para abrir arquivos
        if( (returnval == JFileChooser.CANCEL_OPTION) || returnval == JFileChooser.ERROR_OPTION){
            seg1 = null;
        }
        else{
           seg1 = leArquivo(jFileChooser1.getSelectedFile());
        }
    }//GEN-LAST:event_AbrirSeg1ActionPerformed

    private void MontarSeg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontarSeg1ActionPerformed
        if(seg1!= null){
            m = new Montador(seg1);
            m.montar();
            this.TabDef1 = m.getControllerDefinicao();
            this.TabUso1 = m.getControllerUso();
            this.reloc1 = m.getRelocabilidade();
            m.ImprimeTabUso(TabUso1Area);
            m.ImprimeTabDef(TabDef1Area);
            FileWriter arquivo_w;  
            try {  
                File mont1_f = new File("saidas/mont1.txt");
                arquivo_w = new FileWriter(mont1_f);  
                arquivo_w.write(m.getSAida()); 
                
                LocMont1.setText(""+mont1_f.getAbsoluteFile());
                arquivo_w.close();  
            } catch (IOException e) {  
                //e.printStackTrace();  
            } 
            
        }
    }//GEN-LAST:event_MontarSeg1ActionPerformed

    private void AbrirSeg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirSeg2ActionPerformed
        JFileChooser jFileChooser2;
        jFileChooser2 = new JFileChooser("entradas");   //cria o jfilechooser
        jFileChooser2.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);  //mostrar apenas diretorios e arquivos
        int returnval = jFileChooser2.showOpenDialog(null); //mostra a janela para abrir arquivos
        if( (returnval == JFileChooser.CANCEL_OPTION) || returnval == JFileChooser.ERROR_OPTION){
            seg2 = null;
        }
        else{
           seg2 = leArquivo(jFileChooser2.getSelectedFile());
        }
    }//GEN-LAST:event_AbrirSeg2ActionPerformed

    private void MontarSeg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontarSeg2ActionPerformed
        if(this.TabUso1 != null && seg2!= null){
            m = new Montador(seg2);
            m.montar();
            
            this.TabDef2 = m.getControllerDefinicao();
            this.TabUso2 = m.getControllerUso();
            this.reloc2 = m.getRelocabilidade();
            //this.mont2 = m.getSAida();
            m.ImprimeTabUso(TabUso2Area);
            m.ImprimeTabDef(TabDef2Area);
            FileWriter arquivo_w;
            try {  
                File mont2_f = new File("saidas/mont2.txt");
                arquivo_w = new FileWriter(mont2_f);  
                arquivo_w.write(m.getSAida()); 
                
                LocMont2.setText(""+mont2_f.getAbsoluteFile());
                arquivo_w.close();
                LigadorPS lig = new LigadorPS(this.reloc1, this.getReloc2(), this.TabUso1, this.TabUso2, this.TabDef1, this.TabDef2);
                Frame fr = new Frame(lig);
                fr.setVisible(true);
            } catch (IOException e) {  
                //e.printStackTrace();  
            }
        }
    }//GEN-LAST:event_MontarSeg2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirSeg1;
    private javax.swing.JButton AbrirSeg2;
    private javax.swing.JLabel LocMont1;
    private javax.swing.JLabel LocMont2;
    private javax.swing.JButton MontarSeg1;
    private javax.swing.JButton MontarSeg2;
    private javax.swing.JTextArea TabDef1Area;
    private javax.swing.JTextArea TabDef2Area;
    private javax.swing.JTextArea TabUso1Area;
    private javax.swing.JTextArea TabUso2Area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    public String leArquivo(File arqvo) {
    Scanner scanner;
        try {
            scanner = new Scanner(arqvo);
            scanner.useDelimiter("\\Z");
            return scanner.next();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameMontador.class.getName()).log(Level.SEVERE, null, ex);
        }
    return null;
}

}
